'''In Fibonacci series, every new term is generated by adding the previous two
terms as shown below. Write a program that displays Fibonacci series between 0 to
user input range.
0,1,1,2,3,5,8,13, ... ... ...'''

num = int(input("Enter your number to display it's Fibonazi series "))
num1 = 0
num2 = 1

for i in range(num):
    print(num1)
    add = num1 + num2 
    num1 = num2
    num2 = add
    